# Header
menu:
  Home: /
  Series: /series 
  Archives: /archives
  About: /about
  Projects: https://github.com/Pokoai
  ## Rss: /atom.xml

# Content
excerpt_link: More
prev: Prev
next: Next
## reply: 评论
## share: 分享
fancybox: true

# Sidebar
widgets:
## - search
- category
- music_new
- recent_posts
## - tag
- tagcloud
- wechat


# Miscellaneous
favicon: https://img.arctee.cn/one/favicon.ico

## 网易云音乐插件
music: 
  enable: true
  autoplay: true
  id: 2818034763  
  

## 微信公众号介绍、图片链接
wechat_intro: "请关注我的公众号，获取更多资源："
wechat_img: https://img.arctee.cn/one/pokeai-wechat.png

## 知识星球介绍、图片链接
knowledgePlanet_intro: "加入知识星球，一起交流："
knowledgePlanet_img: https://img.arctee.cn/one/202208201450304.png


## Waline [Waline](https://waline.js.org) 评论
waline_comment: true
## el 和 path 会在页面自动生成，不必加入
waline:
  serverURL: https://comment.pokeai.cn/ # Waline 的服务端地址（必填）
  meta: [nick,mail,link] # waline comment header info
  avatar: robohash # Gravatar头像展示方式。默认值：'mp'【不必填】
  requiredFields: [nick,mail]  # 设置评论者属性必填项。默认值：[]（即匿名）【不必填】
  placeholder: 快来评论吧~  # 评论占位提示
  pageSize: 10 # 评论列表分页，每页条数。默认值：10【不必填】
  copyright: false # 是否显示页脚版权信息。默认值true【不必填】
  
  visitor: # 文章访问量统计。默认值: false【不必填】
  login: # 登录模式状态，默认值：enable（'enable': 启用登录、'disable': 禁用登录，用户只能填写信息评论、'force': 强制登录，用户必须注册并登录才可发布评论）【不必填】
  wordLimit: # 评论字数限制，填入单个数字时为最大字数限制。默认值：0（即不限制）【不必填】
  
  avatarCDN: # 设置Gravatar头像CDN地址。默认值: https://sdn.geekzu.org/avatar/【不必填】
  avatarForce: # 每次访问是否强制拉取最新的评论列表头像。默认值：false【不必填】
  highlight: # 代码高亮显示。默认值：true【不必填】
  mathTagSupport: # 是否注入核外样式以兼容 <math> 显示，默认值：false【不必填】
  emojiCDN: # 设置表情包 CDN。默认值：https://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/【不必填】--即将废弃


# toc
toc:
  top: true
  right: false

rss: /atom.xml
google_analytics:
google_site_verification: 
baidu_site_verification: 
