# Header
menu:
  Home: /
  Series: /series
  Archives: /archives
  About: /about
  Projects: https://github.com/Pokoai

# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
## share: 分享
fancybox: true

# Sidebar
widgets:
- search
- category
- recent_posts
- music
- tag
- tagcloud

# Miscellaneous
google_analytics:
duoshuo_shortname: 
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: https://img.arctee.cn/one/202208070137740.ico
music: 