# Header
menu:
  Home: /
  Series: /series
  Archives: /archives
  About: /about
  Projects: https://github.com/Pokoai
  Rss: /atom.xml

# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
##share: 分享
fancybox: true

# Sidebar
widgets:
- search
- category
- music
- recent_posts
- tag
- tagcloud

# Miscellaneous
google_analytics:
duoshuo_shortname: 
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: 
music: 