# Header
menu:
  Home: /
  Series: /series
  Archives: /archives
  About: /about
  Projects: https://github.com/Pokoai
  ## Nav: https://source.pokeai.cn
  ## Rss: /atom.xml
  Nav: https://nav.pokeai.cn

# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
##share: 分享
fancybox: true

# Sidebar
widgets:


# Miscellaneous
google_analytics:
duoshuo_shortname: 
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: 
music: 
